spring.application.name=auth_post
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_post
spring.datasource.username=postgres
spring.datasource.password=to3847
spring.jpa.hibernate.ddl-auto=update
